name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  packages: write
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      -   uses: googleapis/release-please-action@v4
          id: release
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

      -   name: Checkout
          if: steps.release.outputs.releases_created == 'true'
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

      -   uses: tada5hi/action-docker-image-publish@v3
          if: steps.release.outputs.releases_created == 'true'
          with:
            registryRepository: dnpm-dip/http-polling-module
            registryTag: |
              latest
              ${{ steps.release.outputs['major'] }}.${{ steps.release.outputs['minor'] }}.${{ steps.release.outputs['patch'] }}
